resources:
  - apiVersion: aws.upbound.io/v1beta1
    kind: ProviderConfig
    metadata:
      name: aws-account-1
    spec:
      credentials:
        source: Secret
        secretRef:
          namespace: crossplane-system
          name: aws-iac-secret
          key: credentials